apiVersion: v1
kind: Service
metadata:
  name: nextcloud-mysql
  namespace: nc-sts  
  labels:
    app: nextcloud
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: nextcloud
    tier: mysql
  clusterIP: None
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: nc-sts  
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nc-mysql
  namespace: nc-sts  
  labels:
    app: nextcloud
spec:
  serviceName: nextcloud-mysql
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
      tier: mysql
  template:
    metadata:
      labels:
        app: nextcloud
        tier: mysql
    spec:
      volumes:
        - name: mysql-p-vol
          persistentVolumeClaim:
            claimName: mysql-pvc 
      containers:
      - image: mysql
        name: mysql
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 65534  
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nc-mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: nextcloud
        - name: MYSQL_USER
          value: nextcloud
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nc-mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-p-vol
          mountPath: /var/lib/mysql
