apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  ports:
    - port: 80
  selector:
    app: nextcloud
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nc-pv-claim
  labels:
    app: nextcloud
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
        tier: frontend
    spec:
      securityContext:
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "80"
      containers:
      - image: nextcloud
        name: nextcloud
        securityContext:
          runAsUser: 65534
          runAsGroup: 65534
          allowPrivilegeEscalation: false
          capabilities:
            add: ["SYS_TIME"]
        env:
        - name: MYSQL_HOST
          value: nextcloud-mysql
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nc-mysql-pass
              key: password
        - name: MYSQL_USER
          value: nextcloud
        - name: MYSQL_DATABASE
          value: nextcloud    
        ports:
        - containerPort: 80
          name: nextcloud
        volumeMounts:
        - name: nextcloud-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: nextcloud-persistent-storage
        persistentVolumeClaim:
          claimName: nc-pv-claim

